import fs from 'fs';
import path from 'path';

const sourceBasePath = 'f:/province/省份/image';
const destBasePath = 'f:/province/public/image';

const provinceImageMap = {
  '上海美食图片': { provinceId: 'shanghai', items: [
    { name: '南翔小笼包', file: '1_南翔小笼包.png' },
    { name: '生煎馒头', file: '2_生煎馒头.png' },
    { name: '上海红烧肉', file: '3_上海红烧肉.png' },
    { name: '排骨年糕', file: '4_排骨年糕.png' },
    { name: '糟钵头', file: '5_糟钵头.png' },
    { name: '葱油拌面', file: '6_葱油拌面.jpg' },
    { name: '枫泾丁蹄', file: '7_枫泾丁蹄.png' },
    { name: '水晶虾仁', file: '8_水晶虾仁.png' },
    { name: '八宝鸭', file: '9_八宝鸭.png' },
    { name: '腌笃鲜', file: '10_腌笃鲜.png' },
  ]},
  '云南美食图片': { provinceId: 'yunnan', items: [
    { name: '过桥米线', file: '1_过桥米线.png' },
    { name: '汽锅鸡', file: '2_汽锅鸡.png' },
    { name: '野生菌火锅', file: '3_野生菌火锅.png' },
    { name: '鲜花饼', file: '4_鲜花饼.png' },
    { name: '乳扇', file: '5_乳扇.png' },
    { name: '饵块', file: '6_饵块.png' },
    { name: '傣味手抓饭', file: '7_傣味手抓饭.png' },
    { name: '宣威火腿', file: '8_宣威火腿.png' },
    { name: '牛干巴', file: '9_牛干巴.png' },
  ]},
  '内蒙古美食图片': { provinceId: 'neimenggu', items: [
    { name: '手扒羊肉', file: '1_手扒羊肉.png' },
    { name: '烤全羊', file: '2_烤全羊.png' },
    { name: '蒙古奶茶', file: '3_蒙古奶茶.png' },
    { name: '烧麦', file: '4_烧麦.png' },
    { name: '羊杂碎', file: '5_羊杂碎.png' },
    { name: '奶皮子', file: '6_奶皮子.png' },
    { name: '风干牛肉', file: '7_风干牛肉.png' },
    { name: '炒米', file: '8_炒米.png' },
    { name: '奶豆腐', file: '9_奶豆腐.png' },
  ]},
  '北京美食图片': { provinceId: 'beijing', items: [
    { name: '北京烤鸭', file: '1_北京烤鸭.png' },
    { name: '老北京炸酱面', file: '2_老北京炸酱面.png' },
    { name: '豆汁儿', file: '3_豆汁儿.png' },
    { name: '卤煮火烧', file: '4_卤煮火烧.png' },
    { name: '爆肚', file: '5_爆肚.png' },
    { name: '艾窝窝', file: '6_艾窝窝.png' },
    { name: '焦圈', file: '7_焦圈.png' },
    { name: '糖耳朵', file: '8_糖耳朵.png' },
    { name: '褡裢火烧', file: '9_褡裢火烧.png' },
  ]},
  '台湾美食图片': { provinceId: 'taiwan', items: [
    { name: '蚵仔煎', file: '01_蚵仔煎.jpg' },
    { name: '珍珠奶茶', file: '02_珍珠奶茶.jpg' },
    { name: '卤肉饭', file: '03_卤肉饭.jpg' },
    { name: '凤梨酥', file: '04_凤梨酥.jpg' },
    { name: '大肠蚵仔面线', file: '05_大肠蚵仔面线.jpg' },
    { name: '牛肉面', file: '06_牛肉面.jpg' },
    { name: '担仔面', file: '07_担仔面.jpg' },
    { name: '盐酥鸡', file: '08_盐酥鸡.jpg' },
    { name: '小笼包', file: '09_小笼包.jpg' },
    { name: '剉冰', file: '10_剉冰.jpg' },
  ]},
  '吉林美食图片': { provinceId: 'jilin', items: [
    { name: '延吉冷面', file: '1_延吉冷面.png' },
    { name: '查干湖胖头鱼', file: '2_查干湖胖头鱼.png' },
    { name: '小鸡炖蘑菇', file: '3_小鸡炖蘑菇.png' },
    { name: '猪肉炖粉条', file: '4_猪肉炖粉条.png' },
    { name: '朝鲜族泡菜', file: '5_朝鲜族泡菜.png' },
    { name: '锅包肉', file: '6_锅包肉.png' },
    { name: '打糕', file: '7_打糕.png' },
    { name: '粘豆包', file: '8_粘豆包.png' },
    { name: '朝鲜族冷面汤', file: '9_朝鲜族冷面汤.png' },
    { name: '酱汤饭', file: '10_酱汤饭.png' },
  ]},
  '四川美食图片': { provinceId: 'sichuan', items: [
    { name: '四川火锅', file: '01_四川火锅.jpg' },
    { name: '麻婆豆腐', file: '02_麻婆豆腐.jpg' },
    { name: '回锅肉', file: '03_回锅肉.jpg' },
    { name: '夫妻肺片', file: '04_夫妻肺片.jpg' },
    { name: '水煮牛肉', file: '05_水煮牛肉.jpg' },
    { name: '宫保鸡丁', file: '06_宫保鸡丁.jpg' },
    { name: '钟水饺', file: '07_钟水饺.jpg' },
    { name: '甜皮鸭', file: '08_甜皮鸭.jpg' },
    { name: '赖汤圆', file: '09_赖汤圆.jpg' },
    { name: '张飞牛肉', file: '10_张飞牛肉.jpg' },
  ]},
  '天津美食图片': { provinceId: 'tianjin', items: [
    { name: '狗不理包子', file: '01_狗不理包子.jpg' },
    { name: '煎饼果子', file: '02_煎饼果子.jpg' },
    { name: '耳朵眼炸糕', file: '03_耳朵眼炸糕.jpg' },
    { name: '十八街麻花', file: '04_十八街麻花.jpg' },
    { name: '锅巴菜', file: '05_锅巴菜.jpg' },
    { name: '老爆三', file: '06_老爆三.jpg' },
    { name: '罾蹦鲤鱼', file: '07_罾蹦鲤鱼.jpg' },
    { name: '贴饽饽熬小鱼', file: '08_贴饽饽熬小鱼.jpg' },
    { name: '杨村糕干', file: '09_杨村糕干.jpg' },
  ]},
  '宁夏美食图片': { provinceId: 'ningxia', items: [
    { name: '手抓羊肉', file: '01_手抓羊肉.jpg' },
    { name: '烩羊杂碎', file: '02_烩羊杂碎.jpg' },
    { name: '羊肉臊子面', file: '03_羊肉臊子面.jpg' },
    { name: '中宁蒿子面', file: '04_中宁蒿子面.jpg' },
    { name: '辣糊糊', file: '05_辣糊糊.jpg' },
    { name: '燕面揉揉', file: '06_燕面揉揉.jpg' },
    { name: '吴忠早茶', file: '07_吴忠早茶.jpg' },
    { name: '银川羊杂', file: '08_银川羊杂.jpg' },
    { name: '宁夏手抓', file: '09_宁夏手抓.jpg' },
    { name: '盐池羊肉', file: '10_盐池羊肉.jpg' },
  ]},
  '安徽美食图片': { provinceId: 'anhui', items: [
    { name: '徽州臭鳜鱼', file: '01_徽州臭鳜鱼.jpg' },
    { name: '合肥龙虾', file: '02_合肥龙虾.jpg' },
    { name: '黄山烧饼', file: '03_黄山烧饼.jpg' },
    { name: '芜湖虾籽面', file: '04_芜湖虾籽面.jpg' },
    { name: '淮南牛肉汤', file: '05_淮南牛肉汤.jpg' },
    { name: '阜阳格拉条', file: '06_阜阳格拉条.jpg' },
    { name: '合肥四大名点', file: '07_合肥四大名点.jpg' },
    { name: '蚌埠烧饼夹里脊', file: '08_蚌埠烧饼夹里脊.jpg' },
    { name: '安庆鸡汤泡炒米', file: '09_安庆鸡汤泡炒米.jpg' },
    { name: '滁州雷官板鸭', file: '10_滁州雷官板鸭.jpg' },
  ]},
  '山东美食图片': { provinceId: 'shandong', items: [
    { name: '山东煎饼', file: '01_山东煎饼.jpg' },
    { name: '德州扒鸡', file: '02_德州扒鸡.jpg' },
    { name: '九转大肠', file: '03_九转大肠.jpg' },
    { name: '青岛啤酒', file: '04_青岛啤酒.jpg' },
    { name: '潍坊朝天锅', file: '05_潍坊朝天锅.jpg' },
    { name: '济南油旋', file: '06_济南油旋.jpg' },
    { name: '淄博博山豆腐箱', file: '07_淄博博山豆腐箱.jpg' },
    { name: '山东糖醋鲤鱼', file: '08_山东糖醋鲤鱼.jpg' },
    { name: '济南把子肉', file: '09_济南把子肉.jpg' },
    { name: '微山湖鲤鱼', file: '10_微山湖鲤鱼.jpg' },
  ]},
  '山西美食图片': { provinceId: 'shanxi', items: [
    { name: '刀削面', file: '01_刀削面.jpg' },
    { name: '莜面栲栳栳', file: '02_莜面栲栳栳.jpg' },
    { name: '平遥牛肉', file: '03_平遥牛肉.jpg' },
    { name: '太原头脑', file: '04_太原头脑.jpg' },
    { name: '山西过油肉', file: '05_山西过油肉.jpg' },
    { name: '碗托', file: '06_碗托.jpg' },
    { name: '闻喜煮饼', file: '07_闻喜煮饼.jpg' },
    { name: '山西老陈醋', file: '08_山西老陈醋.jpg' },
    { name: '汾酒', file: '09_汾酒.jpg' },
    { name: '太原灌肠', file: '10_太原灌肠.jpg' },
  ]},
  '广东美食图片': { provinceId: 'guangdong', items: [
    { name: '白切鸡', file: '01_白切鸡.jpg' },
    { name: '烧腊', file: '02_烧腊.jpg' },
    { name: '叉烧饭', file: '03_叉烧饭.jpg' },
    { name: '虾饺', file: '04_虾饺.jpg' },
    { name: '云吞面', file: '05_云吞面.jpg' },
    { name: '煲仔饭', file: '06_煲仔饭.jpg' },
    { name: '潮汕牛肉火锅', file: '07_潮汕牛肉火锅.jpg' },
    { name: '早茶', file: '08_早茶.jpg' },
    { name: '肠粉', file: '09_肠粉.jpg' },
    { name: '糖水', file: '10_糖水.jpg' },
  ]},
  '广西美食图片': { provinceId: 'guangxi', items: [
    { name: '柳州螺蛳粉', file: '01_柳州螺蛳粉.jpg' },
    { name: '桂林米粉', file: '02_桂林米粉.jpg' },
    { name: '南宁老友粉', file: '03_南宁老友粉.jpg' },
    { name: '五色糯米饭', file: '04_五色糯米饭.jpg' },
    { name: '柠檬鸭', file: '05_柠檬鸭.jpg' },
    { name: '豆腐酿', file: '06_豆腐酿.jpg' },
    { name: '梧州龟苓膏', file: '07_梧州龟苓膏.jpg' },
    { name: '荔浦芋扣肉', file: '08_荔浦芋扣肉.jpg' },
    { name: '阳朔啤酒鱼', file: '09_阳朔啤酒鱼.jpg' },
    { name: '玉林牛巴', file: '10_玉林牛巴.jpg' },
  ]},
  '新疆美食图片': { provinceId: 'xinjiang', items: [
    { name: '羊肉串', file: '01_羊肉串.jpg' },
    { name: '大盘鸡', file: '02_大盘鸡.jpg' },
    { name: '烤馕', file: '03_烤馕.jpg' },
    { name: '手抓饭', file: '04_手抓饭.jpg' },
    { name: '拉条子', file: '05_拉条子.jpg' },
    { name: '烤包子', file: '06_烤包子.jpg' },
    { name: '羊杂汤', file: '07_羊杂汤.jpg' },
    { name: '椒麻鸡', file: '08_椒麻鸡.jpg' },
    { name: '炒米粉', file: '09_炒米粉.jpg' },
    { name: '酸奶', file: '10_酸奶.jpg' },
  ]},
  '江苏美食图片': { provinceId: 'jiangsu', items: [
    { name: '南京盐水鸭', file: '01_南京盐水鸭.jpg' },
    { name: '扬州炒饭', file: '02_扬州炒饭.jpg' },
    { name: '松鼠鳜鱼', file: '03_松鼠鳜鱼.jpg' },
    { name: '苏州糕点', file: '04_苏州糕点.jpg' },
    { name: '阳澄湖大闸蟹', file: '05_阳澄湖大闸蟹.jpg' },
    { name: '鸭血粉丝汤', file: '06_鸭血粉丝汤.jpg' },
    { name: '扬州狮子头', file: '07_扬州狮子头.jpg' },
    { name: '无锡小笼包', file: '08_无锡小笼包.jpg' },
    { name: '镇江锅盖面', file: '09_镇江锅盖面.jpg' },
    { name: '淮安软兜长鱼', file: '10_淮安软兜长鱼.jpg' },
  ]},
  '江西美食图片': { provinceId: 'jiangxi', items: [
    { name: '瓦罐汤', file: '01_瓦罐汤.jpg' },
    { name: '南昌拌粉', file: '02_南昌拌粉.jpg' },
    { name: '藜蒿炒腊肉', file: '03_藜蒿炒腊肉.jpg' },
    { name: '米粉肉', file: '04_米粉肉.jpg' },
    { name: '鄱阳湖鱼头', file: '05_鄱阳湖鱼头.jpg' },
    { name: '客家酿豆腐', file: '06_客家酿豆腐.jpg' },
    { name: '碱水粑', file: '07_碱水粑.jpg' },
    { name: '酸菜炒肉', file: '08_酸菜炒肉.jpg' },
    { name: '炒田螺', file: '09_炒田螺.jpg' },
    { name: '糊羹', file: '10_糊羹.jpg' },
  ]},
  '河北美食图片': { provinceId: 'hebei', items: [
    { name: '驴肉火烧', file: '01_驴肉火烧.jpg' },
    { name: '正定八大碗', file: '02_正定八大碗.jpg' },
    { name: '金凤扒鸡', file: '03_金凤扒鸡.jpg' },
    { name: '沧州火锅鸡', file: '04_沧州火锅鸡.jpg' },
    { name: '唐山棋子烧饼', file: '05_唐山棋子烧饼.jpg' },
    { name: '香河肉饼', file: '06_香河肉饼.jpg' },
    { name: '缸炉烧饼', file: '07_缸炉烧饼.jpg' },
    { name: '蔚县豆腐干', file: '08_蔚县豆腐干.jpg' },
    { name: '邯郸永年酥鱼', file: '09_邯郸永年酥鱼.jpg' },
    { name: '莜面窝窝', file: '10_莜面窝窝.jpg' },
  ]},
  '河南美食图片': { provinceId: 'henan', items: [
    { name: '河南烩面', file: '01_河南烩面.jpg' },
    { name: '逍遥镇胡辣汤', file: '02_逍遥镇胡辣汤.jpg' },
    { name: '开封灌汤包', file: '03_开封灌汤包.jpg' },
    { name: '道口烧鸡', file: '04_道口烧鸡.jpg' },
    { name: '洛阳水席', file: '05_洛阳水席.jpg' },
    { name: '濮阳壮馍', file: '06_濮阳壮馍.jpg' },
    { name: '郑州烤鸭', file: '07_郑州烤鸭.jpg' },
    { name: '固始鹅块', file: '08_固始鹅块.jpg' },
    { name: '博望锅盔', file: '09_博望锅盔.jpg' },
  ]},
  '浙江美食图片': { provinceId: 'zhejiang', items: [
    { name: '西湖醋鱼', file: '01_西湖醋鱼.jpg' },
    { name: '龙井虾仁', file: '02_龙井虾仁.jpg' },
    { name: '东坡肉', file: '03_东坡肉.jpg' },
    { name: '叫化鸡', file: '04_叫化鸡.jpg' },
    { name: '金华火腿', file: '05_金华火腿.jpg' },
    { name: '宁波汤团', file: '06_宁波汤团.jpg' },
    { name: '绍兴臭豆腐', file: '07_绍兴臭豆腐.jpg' },
    { name: '温州鱼丸', file: '08_温州鱼丸.jpg' },
    { name: '嘉兴粽子', file: '09_嘉兴粽子.jpg' },
    { name: '片儿川', file: '10_片儿川.jpg' },
  ]},
  '海南美食图片': { provinceId: 'hainan', items: [
    { name: '文昌鸡', file: '01_文昌鸡.jpg' },
    { name: '和乐蟹', file: '02_和乐蟹.jpg' },
    { name: '椰子鸡', file: '03_椰子鸡.jpg' },
    { name: '清补凉', file: '04_清补凉.jpg' },
    { name: '老爸茶', file: '05_老爸茶.jpg' },
    { name: '陵水酸粉', file: '06_陵水酸粉.jpg' },
    { name: '抱罗粉', file: '07_抱罗粉.jpg' },
    { name: '海口斋菜煲', file: '08_海口斋菜煲.jpg' },
    { name: '椰子饭', file: '09_椰子饭.jpg' },
    { name: '海胆蒸蛋', file: '10_海胆蒸蛋.jpg' },
  ]},
  '湖北美食图片': { provinceId: 'hubei', items: [
    { name: '武汉热干面', file: '01_武汉热干面.jpg' },
    { name: '武昌鱼', file: '02_武昌鱼.jpg' },
    { name: '排骨藕汤', file: '03_排骨藕汤.jpg' },
    { name: '潜江油焖大虾', file: '04_潜江油焖大虾.jpg' },
    { name: '襄阳牛肉面', file: '05_襄阳牛肉面.jpg' },
    { name: '沔阳三蒸', file: '06_沔阳三蒸.jpg' },
    { name: '黄石港饼', file: '07_黄石港饼.jpg' },
    { name: '荆州鱼糕', file: '08_荆州鱼糕.jpg' },
    { name: '随州泡泡青', file: '09_随州泡泡青.jpg' },
  ]},
  '湖南美食图片': { provinceId: 'hunan', items: [
    { name: '长沙臭豆腐', file: '01_长沙臭豆腐.jpg' },
    { name: '剁椒鱼头', file: '02_剁椒鱼头.jpg' },
    { name: '常德牛肉粉', file: '03_常德牛肉粉.jpg' },
    { name: '口味虾', file: '04_口味虾.jpg' },
    { name: '辣椒炒肉', file: '05_辣椒炒肉.jpg' },
    { name: '东安鸡', file: '06_东安鸡.jpg' },
    { name: '腊味合蒸', file: '07_腊味合蒸.jpg' },
    { name: '岳阳烧烤', file: '08_岳阳烧烤.jpg' },
    { name: '糖油粑粑', file: '09_糖油粑粑.jpg' },
    { name: '湘西霉豆腐', file: '10_湘西霉豆腐.jpg' },
  ]},
  '澳门美食图片': { provinceId: 'macau', items: [
    { name: '葡式蛋挞', file: '01_葡式蛋挞.jpg' },
    { name: '猪扒包', file: '02_猪扒包.jpg' },
    { name: '竹升面', file: '03_竹升面.jpg' },
    { name: '水蟹粥', file: '04_水蟹粥.jpg' },
    { name: '澳门杏仁饼', file: '05_澳门杏仁饼.jpg' },
    { name: '澳门虾籽面', file: '06_澳门虾籽面.jpg' },
    { name: '澳门烧肉', file: '07_澳门烧肉.jpg' },
    { name: '葡国鸡', file: '08_葡国鸡.jpg' },
    { name: '澳门鱼翅丸', file: '09_澳门鱼翅丸.jpg' },
    { name: '澳门老婆饼', file: '10_澳门老婆饼.jpg' },
  ]},
  '甘肃美食图片': { provinceId: 'gansu', items: [
    { name: '兰州牛肉面', file: '01_兰州牛肉面.jpg' },
    { name: '手抓羊肉', file: '02_手抓羊肉.jpg' },
    { name: '甘肃酿皮', file: '03_甘肃酿皮.jpg' },
    { name: '驴肉黄面', file: '04_驴肉黄面.jpg' },
    { name: '甘肃臊子面', file: '05_甘肃臊子面.jpg' },
    { name: '甘肃羊肉泡馍', file: '06_甘肃羊肉泡馍.jpg' },
    { name: '甘肃炒面片', file: '07_甘肃炒面片.jpg' },
    { name: '甘肃凉面', file: '08_甘肃凉面.jpg' },
    { name: '甘肃烩面', file: '09_甘肃烩面.jpg' },
    { name: '甘肃甜醅子', file: '10_甘肃甜醅子.jpg' },
  ]},
  '福建美食图片': { provinceId: 'fujian', items: [
    { name: '佛跳墙', file: '01_佛跳墙.jpg' },
    { name: '福州鱼丸', file: '02_福州鱼丸.jpg' },
    { name: '沙县小吃', file: '03_沙县小吃.jpg' },
    { name: '厦门沙茶面', file: '04_厦门沙茶面.jpg' },
    { name: '姜母鸭', file: '05_姜母鸭.jpg' },
    { name: '土笋冻', file: '06_土笋冻.jpg' },
    { name: '福州肉燕', file: '07_福州肉燕.jpg' },
    { name: '闽南烧肉粽', file: '08_闽南烧肉粽.jpg' },
    { name: '泉州面线糊', file: '09_泉州面线糊.jpg' },
  ]},
  '西藏美食图片': { provinceId: 'xizang', items: [
    { name: '糌粑', file: '01_糌粑.jpg' },
    { name: '酥油茶', file: '02_酥油茶.jpg' },
    { name: '牦牛肉', file: '03_牦牛肉.jpg' },
    { name: '风干牦牛肉', file: '04_风干牦牛肉.jpg' },
    { name: '青稞酒', file: '05_青稞酒.jpg' },
    { name: '甜茶', file: '06_甜茶.jpg' },
    { name: '藏面', file: '07_藏面.jpg' },
    { name: '牦牛酸奶', file: '08_牦牛酸奶.jpg' },
    { name: '藏香猪', file: '09_藏香猪.jpg' },
    { name: '土豆烧牦牛肉', file: '10_土豆烧牦牛肉.jpg' },
  ]},
  '贵州美食图片': { provinceId: 'guizhou', items: [
    { name: '酸汤鱼', file: '01_酸汤鱼.jpg' },
    { name: '辣子鸡', file: '02_辣子鸡.jpg' },
    { name: '肠旺面', file: '03_肠旺面.jpg' },
    { name: '羊肉粉', file: '04_羊肉粉.jpg' },
    { name: '丝娃娃', file: '05_丝娃娃.jpg' },
    { name: '恋爱豆腐果', file: '06_恋爱豆腐果.jpg' },
    { name: '豆花鱼', file: '07_豆花鱼.jpg' },
    { name: '贵州烙锅', file: '08_贵州烙锅.jpg' },
    { name: '贵州米豆腐', file: '09_贵州米豆腐.jpg' },
    { name: '贵州剔骨鸭', file: '10_贵州剔骨鸭.jpg' },
  ]},
  '辽宁美食图片': { provinceId: 'liaoning', items: [
    { name: '锅包肉', file: '01_锅包肉.jpg' },
    { name: '杀猪菜', file: '02_杀猪菜.jpg' },
    { name: '沈阳鸡架', file: '03_沈阳鸡架.jpg' },
    { name: '铁锅炖大鹅', file: '04_铁锅炖大鹅.jpg' },
    { name: '大连海鲜', file: '05_大连海鲜.jpg' },
    { name: '沈阳回头', file: '06_沈阳回头.jpg' },
    { name: '锦州烧烤', file: '07_锦州烧烤.jpg' },
    { name: '鞍山牛录馅饼', file: '08_鞍山牛录馅饼.jpg' },
    { name: '盘锦河蟹', file: '09_盘锦河蟹.jpg' },
    { name: '朝阳小米', file: '10_朝阳小米.jpg' },
  ]},
  '重庆美食图片': { provinceId: 'chongqing', items: [
    { name: '重庆火锅', file: '01_重庆火锅.jpg' },
    { name: '重庆小面', file: '02_重庆小面.jpg' },
    { name: '酸辣粉', file: '03_酸辣粉.jpg' },
    { name: '毛血旺', file: '04_毛血旺.jpg' },
    { name: '辣子鸡', file: '05_辣子鸡.jpg' },
    { name: '串串香', file: '06_串串香.jpg' },
    { name: '豆花', file: '07_豆花.jpg' },
    { name: '万州烤鱼', file: '08_万州烤鱼.jpg' },
    { name: '泡椒牛蛙', file: '09_泡椒牛蛙.jpg' },
    { name: '山城汤圆', file: '10_山城汤圆.jpg' },
  ]},
  '陕西美食图片': { provinceId: 'shaanxi', items: [
    { name: '羊肉泡馍', file: '01_羊肉泡馍.jpg' },
    { name: '肉夹馍', file: '02_肉夹馍.jpg' },
    { name: '凉皮', file: '03_凉皮.jpg' },
    { name: 'Biángbiáng面', file: '04_Biángbiáng面.jpg' },
    { name: '岐山臊子面', file: '05_岐山臊子面.jpg' },
    { name: '葫芦头泡馍', file: '06_葫芦头泡馍.jpg' },
    { name: '贾三灌汤包', file: '07_贾三灌汤包.jpg' },
    { name: '甑糕', file: '08_甑糕.jpg' },
    { name: '锅盔', file: '09_锅盔.jpg' },
    { name: '荞面饸饹', file: '10_荞面饸饹.jpg' },
  ]},
  '青海美食图片': { provinceId: 'qinghai', items: [
    { name: '手抓羊肉', file: '01_手抓羊肉.jpg' },
    { name: '青海酸奶', file: '02_青海酸奶.jpg' },
    { name: '青海酿皮', file: '03_青海酿皮.jpg' },
    { name: '青海尕面片', file: '04_青海尕面片.jpg' },
    { name: '青海土火锅', file: '05_青海土火锅.jpg' },
    { name: '青海甜醅', file: '06_青海甜醅.jpg' },
    { name: '青海焜锅', file: '07_青海焜锅.jpg' },
    { name: '青海青稞面', file: '08_青海青稞面.jpg' },
    { name: '青海酥油茶', file: '09_青海酥油茶.jpg' },
    { name: '青海糌粑', file: '10_青海糌粑.jpg' },
  ]},
  '香港美食图片': { provinceId: 'hongkong', items: [
    { name: '叉烧', file: '01_叉烧.jpg' },
    { name: '蛋挞', file: '02_蛋挞.jpg' },
    { name: '鱼蛋粉', file: '03_鱼蛋粉.jpg' },
    { name: '丝袜奶茶', file: '04_丝袜奶茶.jpg' },
    { name: '云吞面', file: '05_云吞面.jpg' },
  ]},
};

function copyImage(sourcePath, destPath) {
  try {
    if (!fs.existsSync(path.dirname(destPath))) {
      fs.mkdirSync(path.dirname(destPath), { recursive: true });
    }
    fs.copyFileSync(sourcePath, destPath);
    return true;
  } catch (err) {
    console.error(`复制图片失败 ${sourcePath}: ${err.message}`);
    return false;
  }
}

let foodImagesMap = '';

Object.keys(provinceImageMap).forEach(folderName => {
  const province = provinceImageMap[folderName];
  province.items.forEach(item => {
    const sourcePath = path.join(sourceBasePath, folderName, item.file);
    const destPath = path.join(destBasePath, folderName, item.file);
    
    if (fs.existsSync(sourcePath)) {
      const success = copyImage(sourcePath, destPath);
      if (success) {
        const imagePath = `/image/${folderName}/${item.file}`;
        foodImagesMap += `  '${item.name}': '${imagePath}',\n`;
      }
    } else {
      console.warn(`图片不存在: ${sourcePath}`);
    }
  });
});

console.log('\n=== foodImages 映射表 ===\n');
console.log('const foodImages: {[key: string]: string} = {');
console.log(foodImagesMap);
console.log('};');
console.log('\n=== 图片复制完成 ===');
